name: Zip Files

on:
  release:
    types: [published]
  workflow_dispatch:
jobs:
  zip-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: thedoctor0/zip-release@master
        with:
          filename: MongoConnector.zip

      - name: Upload Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: MongoConnector.zip
          token: ${{ secrets.GITHUB_TOKEN }}
