name: Publish Pugin

on:
  push:
    tags:
      - '*'
  release:
    types: [published]
  workflow_dispatch:
jobs:
  zip-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: thedoctor0/zip-release@master
        with:
          filename: MongoConnector.zip

      - name: Upload Release
        uses: svenstaro/upload-release-action@v2
        with:
          file: MongoConnector.zip
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref }}
          overwrite: true
          
      - name: Upload Release
        uses: kumarabd/trigger-remote-action@v1.0.0
        with:
          repo: "gospodarka-przestrzenna/qgis-plugins.xml"
          version: "latest"
          name: "Publish Plugin"
          token: ${{ secrets.GITHUB_TOKEN }}  
          
